name: RSS Scraper

# Run at the 0th minute of every hour between 13 and 22 UTC.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13-22 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RSS scraper
        run: python rss_parser.py

      # Optionally commit and push updated JSON data if changes were made.
      - name: Commit updated data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add articles_from_rss.json
          git diff --cached --quiet || git commit -m "Update RSS feed data"
          git push
